
defined_elements = ['map', 'name', 'version', 'objective',
'authors', 'contributors', 'author', 'contributor',
'include', 'tutorial', 'stage', 'message', 'line',
'teleport', 'rules', 'rule', 'broadcasts', 'tip',
'alert', 'filter', 'wools', 'wool', 'monument', 'block',
'wool', 'flags', 'post', 'flag', 'net', 'pickup-filter',
'capture-filter', 'pickup-kit', 'drop-kit', 'region',
'respawn-filter', 'score', 'limit', 'cylinder', 'potion',
'not', 'same-team', 'carrying-flag', 'spawns', 'respawn',
'destroyables', 'destroyable', 'cores', 'core', 'king',
'hills', 'hill', 'capture', 'progress', 'cuboid',
'control-points', 'control-point', 'captured',
'player-filter', 'blitz', 'lives', 'broadcastLives', 'time',
'kills', 'deaths', 'box', 'redeemables', 'item', 'ghostsquadron',
'rage', 'teams', 'team', 'players', 'classes', 'class', 'kit',
'kits', 'helmet', 'enchantment', 'attribute', 'can-destroy',
'can-place-on', 'chestplate', 'leggings', 'boots', 'title',
'pages', 'page', 'book', 'material', 'all-blocks', 'item-mods',
'match', 'modify', 'all-materials', 'crafting', 'shaped',
'shapeless', 'smelt', 'disable', 'override', 'override-all',
'result', 'ingredient', 'i', 'row', 'toolrepair', 'tool',
'itemremove', 'itemkeep', 'armorkeep', 'disabledamage', 'damage',
'projectiles', 'projectile', 'destroy-filter', 'modifybowprojectile',
'velocityMod', 'tnt', 'instantignite', 'blockdamage', 'yield',
'power', 'fuse', 'dispenser-tnt-limit', 'dispenser-tnt-multiplier',
'licensing', 'friendly-defuse', 'mobs', 'spawn', 'entitiy', 'all',
'kill-reward', 'kill-rewards', 'gamerules', 'doFireTick',
'doTileDrops', 'doMobLoot', 'mobGriefing', 'naturalRegeneration',
'doDayLightCycle', 'world-borders', 'world-border', 'when',
'timelock', 'maxbuildheight', 'friendlyfire', 'friendlyfirerefund',
'difficulty', 'dimension', 'hunger', 'depletion', 'multitrade',
'any', 'random', 'crouching', 'flying', 'can-fly', 'flag-captured',
'flag-carried', 'flag-dropped', 'flag-returned', 'cause', 'carrying',
'holding', 'always', 'never', 'kill-streak', 'rectangle', 'sphere',
'circle', 'half', 'below', 'empty', 'nowhere', 'everywhere', 'above',
'regions', 'apply', 'negative', 'union', 'complement', 'intersect',
'translate', 'mirror', 'point', 'default', 'lanes', 'lane',
'portals', 'portal', 'destination', 'proximity-alarms',
'proximity-alarm', 'detect', 'notify', 'falling-blocks', 'sticky',
'renewables', 'renewable', 'renew-filter',' replace-filter',
'shuffle-filter', 'block-drops', 'drops',
'experience', 'replacement', 'wrongtool', 'punch', 'trample,',
'fall-chance', 'land-chance', 'fall-speed', 'modes', 'mode',
'?xml', 'if', 'unless', 'gamemode', 'gamemodes', 'filters' '!--
]
for item in defined_elements:
	if '-' in item:
		defined_elements.append(item.replace('-', ''))
